bug: Keep in line with origin/master
It seems like the contents of this branch didn't line up with the one on master.
This made subtree pushes fail:

> nothing to commit, working tree clean
> git push using:  origin gh-pages
> To github.com:Clever/components
>  ! [rejected]        6708fa441d8ad3dd88427ce9dc07038305af39ae -> gh-pages (fetch
>    first)
> error: failed to push some refs to 'git@github.com:Clever/components'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Pulling didn't make sense, because the branch (gh-pages) didn't see any
difference. Trying to pull the changes resulted in "refusing to merge unrelated
histories."

> ❯ git subtree pull --prefix=docs origin gh-pages -d
> command: {pull}
> quiet: {}
> revs: {}
> dir: {docs}
> opts: {origin gh-pages}
> From github.com:Clever/components
>  * branch            gh-pages   -> FETCH_HEAD
> fatal: refusing to merge unrelated histories

Forcing the merge between the two highlighted the differences between the
branches:

❯ git merge -s subtree -Xsubtree="docs" origin/gh-pages
--allow-unrelated-histories
CONFLICT (add/add): Merge conflict in docs/components/MultiSelectView.jsx
Auto-merging docs/components/MultiSelectView.jsx
CONFLICT (add/add): Merge conflict in docs/components/MenuView.jsx
Auto-merging docs/components/MenuView.jsx
CONFLICT (add/add): Merge conflict in docs/components/CopyContainerView.jsx
Auto-merging docs/components/CopyContainerView.jsx
CONFLICT (add/add): Merge conflict in docs/components/AnnouncementBubbleView.jsx
Auto-merging docs/components/AnnouncementBubbleView.jsx
CONFLICT (add/add): Merge conflict in docs/bundle.js
Auto-merging docs/bundle.js
Automatic merge failed; fix conflicts and then commit the result.

By diffing between the two, we could see the exact issues:

> git diff origin/master:docs origin/gh-pages

Hopefully, this allows for the subtree push to still occur, even if master and
gh-pages do not have the exact same history.